# TouchIt development version
name: TouchIt
main: TouchIt\TouchIt
version: "Development Preview"
api: [1.4.1]
load: POSTWORLD
author: Marcus
authors: [Marcus]
description: "This is a powerful sign plugin."
website: https://github.com/SuperMarcus/TouchIt

permissions:
  touchit:
    default: operator
    description: "TouchIt permissions"
    children:
      touchit.sign:
        default: true
        description: "TouchIt sign permissions"
        children:
          touchit.sign.create:
            default: operator
            description: "TouchIt create sign permission"
          touchit.sign.destroy:
            default: operator
            description: "TouchIt delete sign permission"
          touchit.sign.use:
            default: true
            description: "TouchIt use sign permission"
            children:
              touchit.sign.use.world-teleport:
                description: "TouchIt use world teleport sign permission"
                default: true
              touchit.sign.use.portal:
                description: "TouchIt use portal sign permission"
                default: true
              touchit.sign.use.command:
                description: "TouchIt use command sign permission"
                default: true
      touchit.command:
        default: operator
        description: "TouchIt commands permission"