name: TouchIt
main: TouchIt\TouchIt
version: 1.0
api: [1.3.1]
load: POSTWORLD
author: Marcus
authors: [Marcus]
description: "This is a powerful sign teleport plugin."
website: https://github.com/SuperMarcus/TouchIt

# TODO: Commands

permissions:
  touchit:
    description: "TouchIt permission."
    default: notop
    children:
      command:
        description: "TouchIt commands."
        default: notop
        children:
          touchit:
            description: "TouchIt main commands."
            default: notop
            children:
              update:
                description: "TouchIt manual updates commands."
                default: op
      sign:
        description: "TouchIt sign actions permission."
        default: notop
        children:
          build:
            description: "Build sign permission."
            default: op
          break:
            description: "Destroy sign permission."
            default: op
          touch:
            description: "Use sign permission."
            default: notop
            children:
              teleport:
                description: "Use teleport sign permission."
                default: notop