# TouchIt configuration file
# Pyramid development team 2014

# The title for all teleport sign
title:
 teleport: Teleport

# Player limit in one level
MaxPlayers: 20

# Fill with server lobby
# 'MaxPlayers' will not work in this level
# Change it into an none-exists level to switch off this function
MainLevel: world

# Multi-languages support
# Support list: English
language: English

# You may change other way to save data
# Default is SQLite3
Provider: SQLite3

# If not necessary, please switch on this option
SafeSpawn: true