# TouchIt config file
# Pyramid development team 2014

# The title
name: Teleport

# TouchIt language
# Only support English now
Language: English

# Maximum number of persons in one level
maxPeople: 20

# Switch on this option to show count on sign
showCount: true

# Switch on this option to show a warning when some level is full
showFull: true

# Switch on this option to allow none-op player to build touchit sign
allowPlayerBuild: false

# Switch on this option to allow none-op player break touchit sign
allowPlayerBreak: false

# Check level is loaded when building the teleport sign
checkLevel: true

# For the time between place and write the sign
createTimeout: 40

# The time interval between updates the announcement
announcementUpdateInterval: 15
